### PR TITLE
Consistency juren trackerkit

### PR DESCRIPTION
**Pull request by JGoldstone**
Make protocol a two-element object with 'name' and 'version' attributes, with the name of the protocol being limited, for the moment, to 'OpenTrackIO'.

### CODE REVIEW

**Comment by jamesmosys** [comment]
This looks good to me - I'll just quickly run everything tomorrow morning and then merge it. Thanks @JGoldstone

**Comment by jamesmosys** [comment]
Just spotted there's a small C&P error with the schema where you have focus,iris,zoom in there - but I'll fix that tomorrow am before merging ;)

**Comment by JGoldstone** [comment]
Thank you for catching that. I just pushed a commit to the `consistency-juren-trackerkit` branch that embodies the renaming of the Px, Py and Cx, Cy properties of the two shifts to be simply x, y. If you could pick that up too, that would be appreciated.

Will try and evaluate tomorrow if I have any remaining suggestions that would affect what's actually on the wire (vs. a restructuring of the code, later, that would not change the encoding, only how it's generated and/or parsed). I think we are both very keen to finish this up.

**Comment by JGoldstone** [comment]
Just pushed a change to this branch that fixes the copy/paste of FIZ requirements that you noted. Do I need to do something special to get that fix included with the PR that you would be merging, or is it good enough that it's on the same branch? My lack of breadth with GitHub workflows is showing, I'm afraid.

**Pull request merged**
