### PR TITLE
Fix StrictlyPositiveRationalParameter and align it with OpenEXR practice

### LINKED ISSUE #90: Change denominator check in strictly positive rational parameters
At the moment, StrictlyPositiveRationalParameter instances have a validate method that checks to see if the denominator is in the range `(0, (1<<31)-1]`. If the denominator were changed to support integers in the range `(0, (1<<31)-1]`, then strictly positive rational parameter instances could be mapped directly into OpenEXR `Rational` instances.

### LINKED ISSUE #98: StrictlyPostiveRationalParameter incorrectly permits numerators equal to 0
https://github.com/SMPTE/ris-osvp-metadata-camdkit/blob/7c57ef0c80b9cdd4e2bf9f39b80d841ff92fdca8/src/main/python/camdkit/framework.py#L148

... and there is a typo in the name (Postive  -> Positive)

### LINKED ISSUE #99: Rational denominator range should be (0, 4,294,967,295]
This will align camdkit rationals with [OpenEXR rationals](https://github.com/AcademySoftwareFoundation/openexr/blob/159e57120dae5e587454e0d4bd916c792831a8ce/src/lib/OpenEXR/ImfRational.h#L32C7-L32C7).

https://github.com/SMPTE/ris-osvp-metadata-camdkit/blob/7c57ef0c80b9cdd4e2bf9f39b80d841ff92fdca8/src/main/python/camdkit/framework.py#L148

### PR DESCRIPTION
**Pull request by palemieux**
Closes #99 
Closes #98

### CODE REVIEW

**Comment by JGoldstone** [comment]
I can see that I made an error in the original Issue, where I had hoped to map directly into an OpenEXR Imf::Rational, which has a signed 32-bit numerator and an unsigned 32-bit denominator. To map to and from Rationals the denominator check would have to be against `(1<<32)-1`, not `(1<<31)-1` as I had then stated.

Does that make sense, or am I missing something somewhere? The simplest ideas are the easiest to engender blind spots.

If ti does make sense, what is my best course of action to get an appropriate denominator range check? You've already merged into the base branch, I think, so ... start a new PR?

**Comment by palemieux** [comment]
> I can see that I made an error in the original Issue, where I had hoped to map directly into an OpenEXR Imf::Rational, which has a signed 32-bit numerator and an unsigned 32-bit denominator. To map to and from Rationals the denominator check would have to be against `(1<<32)-1`, not `(1<<31)-1` as I had then stated.

See https://github.com/SMPTE/ris-osvp-metadata-camdkit/pull/95/files

**Comment by palemieux** [comment]
@JGoldstone #95 adds a signed rational type. Ok?

**Comment by palemieux** [comment]
@JGoldstone Does this work better?

https://github.com/SMPTE/ris-osvp-metadata-camdkit/pull/96/commits/c1d36460211f094c74fc88c29ce1810d72e64443

**Comment by JGoldstone** [comment]
Yes, that does it for me and strictly positive rationals, thank you.

**Pull request merged**
